version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: rzpanda-db-local
    restart: always
    environment:
      POSTGRES_USER: rzpanda
      POSTGRES_PASSWORD: rzpanda_dev_password
      POSTGRES_DB: rzpanda_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
